library(plotly)
library(dplyr)
library(tidyr)
library(ggplot2)
library(e1071)
library(openintro)
income=read.csv(file.choose(), header=TRUE)
s = sapply(income, function(x) sum(is.na(x)))
summary(income)
head(income)
income$Subjectfact=as.factor(income$Subject)
income$Educfact=as.factor(income$Educ)
str(income)
t.test(Income2005~Educfact, data=income, alternative='less', mu=0, alpha=0.05)
nrow(income %>% filter(income$Educ==12))
nrow(income %>% filter(income$Educ==16))
income %>% ggplot(aes(x=Income2005))+geom_histogram()+facet_wrap(~Educfact)
income %>% ggplot(aes(x=Educfact, y=Income2005))+geom_boxplot()
a= income %>% filter(income$Educ==12)
b= income %>% filter(income$Educ==16)

qqnorm(a$Income2005, pch=1, xlab='12 years education')
qqline(a$Income2005, col='steelblue', lwd=2)

qqnorm(b$Income2005, pch=1, xlab='16 years education')
qqline(b$Income2005, col='steelblue', lwd=2)
skewness(a$Income2005)
skewness(b$Income2005)
skewness(a$Income2005log)
skewness(b$Income2005log)

a %>% ggplot(aes(x=Income2005+1)) + geom_histogram()+scale_x_log10()+scale_y_log10()
b %>% ggplot(aes(x=Income2005+1)) + geom_histogram()+scale_x_log10()+scale_y_log10()
income$Income2005log=log1p(income$Income2005+1)

income %>% ggplot(aes(x=Income2005log))+geom_histogram()+facet_wrap(~Educfact)
income %>% ggplot(aes(x=Educfact, y=Income2005log))+geom_boxplot()
qqnorm(a$Income2005log, pch=1, xlab='12 years education')
qqline(a$Income2005log, col='steelblue', lwd=2)

qqnorm(b$Income2005log, pch=1, xlab='16 years education')
qqline(b$Income2005log, col='steelblue', lwd=2)
t.test(Income2005log ~ Educfact, data=income, alternative = 'two.sided', mu=0, var.equal=TRUE)
t.test(b$Income2005log, a$Income2005log, data=income, alternative = 'two.sided', mu=0, var.equal=TRUE)
t.test(b$Income2005log, a$Income2005log, data=income, alternative = 'greater', mu=0, var.equal=TRUE)
t.test(b$Income2005, a$Income2005, data=income, alternative = 'two.sided', mu=0)
qt(0.95, 1424)

tuition_instate=c(1000,4000,5000,8000,40000)
mean(tuition_instate)
sd(tuition_instate)
(40000-mean(tuition_instate))/sd(tuition_instate)

qqnorm(tuition_instate,xlab='instate')
qqline(tuition_instate)


tuition_outstate=c(3000,8000,30000,32000,40000)
mean(tuition_outstate)
sd(tuition_outstate)
(8000-mean(tuition_outstate))/sd(tuition_outstate)

qqnorm(tuition_outstate, xlab='outstate')
qqline(tuition_outstate)